### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/mciwb#17]
- [x] add a switches modue
  - [x]  place a switch/lever/pressure plate etc in the world and hook its activation to a python function
- [x] Nice profiles functions in mcwb - elipse, rectangle, others?
- [ ] documentation
  - [x] restructure into four quadrant
  - [ ] tutorials
    - [x] setup of python/vscode/docker/
    - [x] fundamentals of python (link to beginner course somewhere)
    - [x] basic interaction with the world
    - [x] making .py files
    - [x] functions
      - [ ] box
      - [ ] pyramid
      - [ ] spooky pyramid
      - [ ] crazy rollercoaster (to be written)
    - [ ] advanced
      - [ ] adding sign control to the world
      - [x] switches with functions 
      - [ ] using monitoring - make spooky pyramid work in background

**Comment by gilesknap** [comment]
I'm going to abandon the tutorials.

Looking back at them in hindsight I just don't think I'm a great teacher - they introduce new concepts and then you get pretty big code blocks using that almost immediately.

Will continue to maintain this as a fun library.
